changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - restyled-io
  categories:
  
    - title: Wallet
      labels:
        - Wallet

    - title: Accounts
      labels:
        - Accounts

    - title: APP
      labels:
        - APP

    - title: Auto-Builders
      labels:
        - Auto-Builders

    - title: Backup
      labels:
        - Backup

    - title: Block
      labels:
        - Block
        - Block-Time-Optimizer
        - Hash-Calculation

    - title: Transactions
      labels:
        - Send
        - Transactions      

    - title: CLI
      labels:
        - CLI-Menu
        - CLI-Parameters

    - title: Connection
      labels:
        - Connection
        - Node
        - API

    - title: Consensus
      labels:
        - Consensus

    - title: Package
      labels:
        - Docker
        - Setup
        - Setups

    - title: Documentation
      labels:
        - Documentation

    - title: Tests
      labels:
        - Functional-Test
        - Stability-Test
        - Unit-Test
        - Test-Environments
        - Tests

    - title: GitHub
      labels:
        - Github-Actions

    - title: Google
      labels:
        - Google-Cloud-Shell

    - title: GUI
      labels:
        - GUI

    - title: Licence
      labels:
        - Licence

    - title: Logging
      labels:
        - Logging

    - title: Debugging
      labels:
        - Debugging

    - title: Release
      labels:
        - Minor
        - Major
        - Release
        - Path

    - title: Performance-Optimization
      labels:
        - Performance-Optimization

    - title: Security
      labels:
        - Security
        - Vulnerability

    - title: Platform
      labels:
        - Windows

    - title: Requirements
      labels:
        - Dependencies

    - title: Research
      labels:
        - Research

    - title: Settings
      labels:
        - Settings

    - title: Status
      labels:
        - Status


    - title: Other Changes
      labels:
        - "*"
